---
title: "Home"
subtitle: "Template for development of regional lab manuals as part of the Passive Acoustic Monitoring Strategic Initiative"
page-layout: full
---

## PAM SI Lab Manual Template

A key priority of the PAM SI team is to leverage GitHub as a collaboration and coordination tool, while utilizing its project management tools. To achieve this, we propose the development of national and regional lab manuals. These manuals will serve as the primary storage location for all lab related information, including methods, data management, and contribute to the open science framework we aim to adopt.

## How To Use This Template

This template will create a Quarto website that each lab can copy and edit with their own lab information. Follow the steps below to copy this template to your lab's GitHub

1.  

### Required Pages

In order to keep consistency between science centers, the following sections/pages will be required in all lab manuals. These will be directly linked to the National PAM Repository. The links will direct you to the associated template page with more directions on what to include.

-   Home Page (this page): Edit this page to include an introduction to your lab, projects you are working on, etc.
-   [Lab Management](https://nmfs-ost.github.io/PAM_template_lab_manual/content/LabManagement.html)
-   [Data Management](https://nmfs-ost.github.io/PAM_template_lab_manual/content/DataManagement.html)
-   [Hardware](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Hardware.html)
-   [Software](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Software.html)
-   [Analysis](https://nmfs-ost.github.io/PAM_template_lab_manual/content/AnalysisMethods.html)
-   [Reporting](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Reporting.html)

### Optional Pages

Here are some more ideas for pages to include in your lab manual. These are optional and will not be linked to the main National PAM Repo, but they may be helpful for your team

-   [Shared values/lab culture](https://nmfs-ost.github.io/PAM_template_lab_manual/content/SharedValues.html)
-   [Onboarding](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Onboarding.html)
-   [Offboarding](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Offboarding.html)
-   [Field Methods](https://nmfs-ost.github.io/PAM_template_lab_manual/content/FieldMethods.html)
-   [Open Science](https://nmfs-ost.github.io/PAM_template_lab_manual/content/OpenScience.html)
-   [Publications/Presentations](https://nmfs-ost.github.io/PAM_template_lab_manual/content/PublicationsPresentations.html)
-   [Resources](https://nmfs-ost.github.io/PAM_template_lab_manual/content/Resources.html)

## Example Manuals

Here are two lab manuals to pull inspiration from

-   [SWFSC Southwest Acoustic Ecology Lab Manual](https://sael-swfsc.github.io/SAEL-lab-manual/content/media.html)
-   [Faylab Manual](https://thefaylab.github.io/lab-manual/)
